language: go
go:
  - 1.5.1
install:
  - mkdir $GOPATH/github.com
  - mkdir $GOPATH/github.com/spamguy
  - cd $GOPATH/github.com/spamguy
  - npm install -g mocha
  - go get -u github.com/gopherjs/gopherjs
  - git clone https://github.com/spamguy/godip.git
  - cd $HOME
  - gopherjs build
before_script:
  - git clone https://github.com/spamguy/diplomacy-variants.git variants
