language: go
go:
  - 1.5.1
install:
  - cd $HOME/gopath/src/github.com/spamguy
  - npm install -g mocha
  - go get -u github.com/gopherjs/gopherjs
  - git clone https://github.com/spamguy/godip.git
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/spamguy/diplomacy-variants.git variants
  - npm install
  - gopherjs build
script:
  - mocha -R dot
